version: '3'

services:
  pokemon-graphdb:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - 10.2.0
    # command: -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
    ports:
      - 7200:7200
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g -Dgraphdb.home=/opt/graphdb/home -Dgraphdb.home.data=/opt/graphdb/home/data -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import -Dgraphdb.workbench.cors.enable=true -Denable-context-index=true -Dentity-pool-implementation=transactional -Dhealth.max.query.time.seconds=60 -Dgraphdb.append.request.id.headers=true -Dreuse.vars.in.subselects=true -Dgraphdb.connector.maxHttpHeaderSize=65536
